"""frankfurterapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from frankfurterapi.api_helper import APIHelper
from frankfurterapi.models.peg import Peg


class CurrencyDetail(object):
    """Implementation of the 'CurrencyDetail' model.

    Attributes:
        iso_code (str): ISO 4217 currency code
        iso_numeric (str): ISO 4217 numeric code
        name (str): Full currency name
        symbol (str): Currency symbol
        providers (List[str]): Provider keys that publish this currency
        peg (Peg): Peg metadata, present only for pegged currencies
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "iso_code": "iso_code",
        "name": "name",
        "iso_numeric": "iso_numeric",
        "symbol": "symbol",
        "providers": "providers",
        "peg": "peg",
    }

    _optionals = [
        "iso_numeric",
        "symbol",
        "providers",
        "peg",
    ]

    _nullables = [
        "iso_numeric",
        "symbol",
    ]

    def __init__(
        self,
        iso_code=None,
        name=None,
        iso_numeric=APIHelper.SKIP,
        symbol=APIHelper.SKIP,
        providers=APIHelper.SKIP,
        peg=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CurrencyDetail instance."""
        # Initialize members of the class
        self.iso_code = iso_code
        if iso_numeric is not APIHelper.SKIP:
            self.iso_numeric = iso_numeric
        self.name = name
        if symbol is not APIHelper.SKIP:
            self.symbol = symbol
        if providers is not APIHelper.SKIP:
            self.providers = providers
        if peg is not APIHelper.SKIP:
            self.peg = peg

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        iso_code =\
            dictionary.get("iso_code")\
            if dictionary.get("iso_code")\
                else None
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        iso_numeric =\
            dictionary.get("iso_numeric")\
            if "iso_numeric" in dictionary.keys()\
                else APIHelper.SKIP
        symbol =\
            dictionary.get("symbol")\
            if "symbol" in dictionary.keys()\
                else APIHelper.SKIP
        providers =\
            dictionary.get("providers")\
            if dictionary.get("providers")\
                else APIHelper.SKIP
        peg =\
            Peg.from_dictionary(
                dictionary.get("peg"))\
                if "peg" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(iso_code,
                   name,
                   iso_numeric,
                   symbol,
                   providers,
                   peg,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _iso_code=self.iso_code
        _iso_numeric=(
            self.iso_numeric
            if hasattr(self, "iso_numeric")
            else None
        )
        _name=self.name
        _symbol=(
            self.symbol
            if hasattr(self, "symbol")
            else None
        )
        _providers=(
            self.providers
            if hasattr(self, "providers")
            else None
        )
        _peg=(
            self.peg
            if hasattr(self, "peg")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"iso_code={_iso_code!r}, "
            f"iso_numeric={_iso_numeric!r}, "
            f"name={_name!r}, "
            f"symbol={_symbol!r}, "
            f"providers={_providers!r}, "
            f"peg={_peg!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _iso_code=self.iso_code
        _iso_numeric=(
            self.iso_numeric
            if hasattr(self, "iso_numeric")
            else None
        )
        _name=self.name
        _symbol=(
            self.symbol
            if hasattr(self, "symbol")
            else None
        )
        _providers=(
            self.providers
            if hasattr(self, "providers")
            else None
        )
        _peg=(
            self.peg
            if hasattr(self, "peg")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"iso_code={_iso_code!s}, "
            f"iso_numeric={_iso_numeric!s}, "
            f"name={_name!s}, "
            f"symbol={_symbol!s}, "
            f"providers={_providers!s}, "
            f"peg={_peg!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
