"""frankfurterapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from frankfurterapi.api_helper import APIHelper


class Peg(object):
    """Implementation of the 'Peg' model.

    Peg metadata, present only for pegged currencies

    Attributes:
        base (str): The model property of type str.
        rate (float): The model property of type float.
        authority (str): The model property of type str.
        source (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "base": "base",
        "rate": "rate",
        "authority": "authority",
        "source": "source",
    }

    _optionals = [
        "base",
        "rate",
        "authority",
        "source",
    ]

    def __init__(
        self,
        base=APIHelper.SKIP,
        rate=APIHelper.SKIP,
        authority=APIHelper.SKIP,
        source=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Peg instance."""
        # Initialize members of the class
        if base is not APIHelper.SKIP:
            self.base = base
        if rate is not APIHelper.SKIP:
            self.rate = rate
        if authority is not APIHelper.SKIP:
            self.authority = authority
        if source is not APIHelper.SKIP:
            self.source = source

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        base =\
            dictionary.get("base")\
            if dictionary.get("base")\
                else APIHelper.SKIP
        rate =\
            dictionary.get("rate")\
            if dictionary.get("rate")\
                else APIHelper.SKIP
        authority =\
            dictionary.get("authority")\
            if dictionary.get("authority")\
                else APIHelper.SKIP
        source =\
            dictionary.get("source")\
            if dictionary.get("source")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(base,
                   rate,
                   authority,
                   source,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _base=(
            self.base
            if hasattr(self, "base")
            else None
        )
        _rate=(
            self.rate
            if hasattr(self, "rate")
            else None
        )
        _authority=(
            self.authority
            if hasattr(self, "authority")
            else None
        )
        _source=(
            self.source
            if hasattr(self, "source")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"base={_base!r}, "
            f"rate={_rate!r}, "
            f"authority={_authority!r}, "
            f"source={_source!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _base=(
            self.base
            if hasattr(self, "base")
            else None
        )
        _rate=(
            self.rate
            if hasattr(self, "rate")
            else None
        )
        _authority=(
            self.authority
            if hasattr(self, "authority")
            else None
        )
        _source=(
            self.source
            if hasattr(self, "source")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"base={_base!s}, "
            f"rate={_rate!s}, "
            f"authority={_authority!s}, "
            f"source={_source!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
