"""frankfurterapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
import dateutil.parser

from frankfurterapi.api_helper import APIHelper


class Provider2(object):
    """Implementation of the 'Provider2' model.

    Attributes:
        key (str): Provider key
        date (date): Provider observation date used for this entry
        rate (float): Provider's rate, rebased to the row's base
        excluded (bool): Present and true when this entry did not contribute to the
            blended rate
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "key": "key",
        "date": "date",
        "rate": "rate",
        "excluded": "excluded",
    }

    _optionals = [
        "excluded",
    ]

    def __init__(
        self,
        key=None,
        date=None,
        rate=None,
        excluded=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Provider2 instance."""
        # Initialize members of the class
        self.key = key
        self.date = date
        self.rate = rate
        if excluded is not APIHelper.SKIP:
            self.excluded = excluded

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        key =\
            dictionary.get("key")\
            if dictionary.get("key")\
                else None
        date = dateutil.parser.parse(
            dictionary.get("date")).date()\
            if dictionary.get("date") else None
        rate =\
            dictionary.get("rate")\
            if dictionary.get("rate")\
                else None
        excluded =\
            dictionary.get("excluded")\
            if "excluded" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(key,
                   date,
                   rate,
                   excluded,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _key=self.key
        _date=self.date
        _rate=self.rate
        _excluded=(
            self.excluded
            if hasattr(self, "excluded")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"key={_key!r}, "
            f"date={_date!r}, "
            f"rate={_rate!r}, "
            f"excluded={_excluded!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _key=self.key
        _date=self.date
        _rate=self.rate
        _excluded=(
            self.excluded
            if hasattr(self, "excluded")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"key={_key!s}, "
            f"date={_date!s}, "
            f"rate={_rate!s}, "
            f"excluded={_excluded!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
