"""frankfurterapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
import dateutil.parser

from frankfurterapi.api_helper import APIHelper


class Provider(object):
    """Implementation of the 'Provider' model.

    Attributes:
        key (str): Provider identifier
        name (str): Full provider name
        country_code (str): ISO 3166-1 alpha-2 country code
        rate_type (str): Official rate type as used by the source
        pivot_currency (str): Base currency for published rates
        data_url (str): Link to the data source
        terms_url (str): Link to terms of use
        start_date (date): Earliest available date
        end_date (date): Latest available date
        publish_cadence (PublishCadence): How often the provider publishes rates.
            Determines the unit of publishes_missed: a count of days, ISO weeks, or
            calendar months. Null for historical-only providers with no scheduled
            cadence.
        publishes_missed (int): Number of expected publishes missed since end_date,
            in units of publish_cadence. For daily providers, counts scheduled
            publish days strictly between end_date and today. For weekly and monthly
            providers, counts ISO weeks or calendar months between the latest
            imported bucket and the bucket whose publish window has already started.
            Null when the provider has no scheduled cadence or no imported data.
        currencies (List[str]): Currency codes covered by this provider
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "key": "key",
        "name": "name",
        "currencies": "currencies",
        "country_code": "country_code",
        "rate_type": "rate_type",
        "pivot_currency": "pivot_currency",
        "data_url": "data_url",
        "terms_url": "terms_url",
        "start_date": "start_date",
        "end_date": "end_date",
        "publish_cadence": "publish_cadence",
        "publishes_missed": "publishes_missed",
    }

    _optionals = [
        "country_code",
        "rate_type",
        "pivot_currency",
        "data_url",
        "terms_url",
        "start_date",
        "end_date",
        "publish_cadence",
        "publishes_missed",
    ]

    _nullables = [
        "country_code",
        "rate_type",
        "pivot_currency",
        "data_url",
        "terms_url",
        "start_date",
        "end_date",
        "publish_cadence",
        "publishes_missed",
    ]

    def __init__(
        self,
        key=None,
        name=None,
        currencies=None,
        country_code=APIHelper.SKIP,
        rate_type=APIHelper.SKIP,
        pivot_currency=APIHelper.SKIP,
        data_url=APIHelper.SKIP,
        terms_url=APIHelper.SKIP,
        start_date=APIHelper.SKIP,
        end_date=APIHelper.SKIP,
        publish_cadence=APIHelper.SKIP,
        publishes_missed=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Provider instance."""
        # Initialize members of the class
        self.key = key
        self.name = name
        if country_code is not APIHelper.SKIP:
            self.country_code = country_code
        if rate_type is not APIHelper.SKIP:
            self.rate_type = rate_type
        if pivot_currency is not APIHelper.SKIP:
            self.pivot_currency = pivot_currency
        if data_url is not APIHelper.SKIP:
            self.data_url = data_url
        if terms_url is not APIHelper.SKIP:
            self.terms_url = terms_url
        if start_date is not APIHelper.SKIP:
            self.start_date = start_date
        if end_date is not APIHelper.SKIP:
            self.end_date = end_date
        if publish_cadence is not APIHelper.SKIP:
            self.publish_cadence = publish_cadence
        if publishes_missed is not APIHelper.SKIP:
            self.publishes_missed = publishes_missed
        self.currencies = currencies

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        key =\
            dictionary.get("key")\
            if dictionary.get("key")\
                else None
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        currencies =\
            dictionary.get("currencies")\
            if dictionary.get("currencies")\
                else None
        country_code =\
            dictionary.get("country_code")\
            if "country_code" in dictionary.keys()\
                else APIHelper.SKIP
        rate_type =\
            dictionary.get("rate_type")\
            if "rate_type" in dictionary.keys()\
                else APIHelper.SKIP
        pivot_currency =\
            dictionary.get("pivot_currency")\
            if "pivot_currency" in dictionary.keys()\
                else APIHelper.SKIP
        data_url =\
            dictionary.get("data_url")\
            if "data_url" in dictionary.keys()\
                else APIHelper.SKIP
        terms_url =\
            dictionary.get("terms_url")\
            if "terms_url" in dictionary.keys()\
                else APIHelper.SKIP
        if "start_date" in dictionary.keys():
            start_date = dateutil.parser.parse(
                dictionary.get("start_date")).date()\
                if dictionary.get("start_date") else None

        else:
            start_date = APIHelper.SKIP
        if "end_date" in dictionary.keys():
            end_date = dateutil.parser.parse(
                dictionary.get("end_date")).date()\
                if dictionary.get("end_date") else None

        else:
            end_date = APIHelper.SKIP
        publish_cadence =\
            dictionary.get("publish_cadence")\
            if "publish_cadence" in dictionary.keys()\
                else APIHelper.SKIP
        publishes_missed =\
            dictionary.get("publishes_missed")\
            if "publishes_missed" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(key,
                   name,
                   currencies,
                   country_code,
                   rate_type,
                   pivot_currency,
                   data_url,
                   terms_url,
                   start_date,
                   end_date,
                   publish_cadence,
                   publishes_missed,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _key=self.key
        _name=self.name
        _country_code=(
            self.country_code
            if hasattr(self, "country_code")
            else None
        )
        _rate_type=(
            self.rate_type
            if hasattr(self, "rate_type")
            else None
        )
        _pivot_currency=(
            self.pivot_currency
            if hasattr(self, "pivot_currency")
            else None
        )
        _data_url=(
            self.data_url
            if hasattr(self, "data_url")
            else None
        )
        _terms_url=(
            self.terms_url
            if hasattr(self, "terms_url")
            else None
        )
        _start_date=(
            self.start_date
            if hasattr(self, "start_date")
            else None
        )
        _end_date=(
            self.end_date
            if hasattr(self, "end_date")
            else None
        )
        _publish_cadence=(
            self.publish_cadence
            if hasattr(self, "publish_cadence")
            else None
        )
        _publishes_missed=(
            self.publishes_missed
            if hasattr(self, "publishes_missed")
            else None
        )
        _currencies=self.currencies
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"key={_key!r}, "
            f"name={_name!r}, "
            f"country_code={_country_code!r}, "
            f"rate_type={_rate_type!r}, "
            f"pivot_currency={_pivot_currency!r}, "
            f"data_url={_data_url!r}, "
            f"terms_url={_terms_url!r}, "
            f"start_date={_start_date!r}, "
            f"end_date={_end_date!r}, "
            f"publish_cadence={_publish_cadence!r}, "
            f"publishes_missed={_publishes_missed!r}, "
            f"currencies={_currencies!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _key=self.key
        _name=self.name
        _country_code=(
            self.country_code
            if hasattr(self, "country_code")
            else None
        )
        _rate_type=(
            self.rate_type
            if hasattr(self, "rate_type")
            else None
        )
        _pivot_currency=(
            self.pivot_currency
            if hasattr(self, "pivot_currency")
            else None
        )
        _data_url=(
            self.data_url
            if hasattr(self, "data_url")
            else None
        )
        _terms_url=(
            self.terms_url
            if hasattr(self, "terms_url")
            else None
        )
        _start_date=(
            self.start_date
            if hasattr(self, "start_date")
            else None
        )
        _end_date=(
            self.end_date
            if hasattr(self, "end_date")
            else None
        )
        _publish_cadence=(
            self.publish_cadence
            if hasattr(self, "publish_cadence")
            else None
        )
        _publishes_missed=(
            self.publishes_missed
            if hasattr(self, "publishes_missed")
            else None
        )
        _currencies=self.currencies
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"key={_key!s}, "
            f"name={_name!s}, "
            f"country_code={_country_code!s}, "
            f"rate_type={_rate_type!s}, "
            f"pivot_currency={_pivot_currency!s}, "
            f"data_url={_data_url!s}, "
            f"terms_url={_terms_url!s}, "
            f"start_date={_start_date!s}, "
            f"end_date={_end_date!s}, "
            f"publish_cadence={_publish_cadence!s}, "
            f"publishes_missed={_publishes_missed!s}, "
            f"currencies={_currencies!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
