"""frankfurterapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class PublishCadence(object):
    """Implementation of the 'PublishCadence' enum.

    How often the provider publishes rates. Determines the unit of publishes_missed:
    a count of days, ISO weeks, or calendar months. Null for historical-only
    providers with no scheduled cadence.

    Attributes:
        DAILY: The enum member of type str.
        WEEKLY: The enum member of type str.
        MONTHLY: The enum member of type str.

    """

    DAILY = "daily"

    WEEKLY = "weekly"

    MONTHLY = "monthly"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
