"""frankfurterapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
import dateutil.parser

from frankfurterapi.api_helper import APIHelper
from frankfurterapi.models.provider_2 import (
    Provider2,
)


class Rate(object):
    """Implementation of the 'Rate' model.

    Attributes:
        date (date): The date of the rate
        base (str): Base currency code
        quote (str): Quote currency code
        rate (float): Exchange rate value
        providers (List[Provider2]): Per-provider rates for this pair. Present only
            when `expand=providers` is set. Each entry has the provider's observation
            date and published rate (rebased to the row's base). Entries with
            `excluded: true` did not contribute to the blended `rate` — either
            flagged as outliers by the consensus filter, or overridden by a currency
            peg. Omitted on synthesized peg rows where no provider published the
            quote.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "date": "date",
        "base": "base",
        "quote": "quote",
        "rate": "rate",
        "providers": "providers",
    }

    _optionals = [
        "providers",
    ]

    def __init__(
        self,
        date=None,
        base=None,
        quote=None,
        rate=None,
        providers=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Rate instance."""
        # Initialize members of the class
        self.date = date
        self.base = base
        self.quote = quote
        self.rate = rate
        if providers is not APIHelper.SKIP:
            self.providers = providers

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        date = dateutil.parser.parse(
            dictionary.get("date")).date()\
            if dictionary.get("date") else None
        base =\
            dictionary.get("base")\
            if dictionary.get("base")\
                else None
        quote =\
            dictionary.get("quote")\
            if dictionary.get("quote")\
                else None
        rate =\
            dictionary.get("rate")\
            if dictionary.get("rate")\
                else None
        providers = None
        if dictionary.get("providers") is not None:
            providers = [
                Provider2.from_dictionary(x)
                    for x in dictionary.get("providers")
            ]
        else:
            providers = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(date,
                   base,
                   quote,
                   rate,
                   providers,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _date=self.date
        _base=self.base
        _quote=self.quote
        _rate=self.rate
        _providers=(
            self.providers
            if hasattr(self, "providers")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"date={_date!r}, "
            f"base={_base!r}, "
            f"quote={_quote!r}, "
            f"rate={_rate!r}, "
            f"providers={_providers!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _date=self.date
        _base=self.base
        _quote=self.quote
        _rate=self.rate
        _providers=(
            self.providers
            if hasattr(self, "providers")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"date={_date!s}, "
            f"base={_base!s}, "
            f"quote={_quote!s}, "
            f"rate={_rate!s}, "
            f"providers={_providers!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
